### ISSUE TITLE
FYI: GeckoMoped

### ISSUE THREAD

**Issue by multiplemonomials** [scivision/geckodrive#1]
Sorry, this isn't an actual issue, just wanted to let you guys know about a project we've been working on at my lab: [GeckoMoped](https://github.com/USCRPL/GeckoMoped).

Like you guys, we had frequent connection issues using the stock GeckoMotion software, and decided to do something about it.  So, we used the original GeckoMotion as a starting point to produce GeckoMoped, a much-improved version with fixes for many of the connection issues that plagued the original program suffers (a full writeup of the issue is on our repository).  It also adds a complete Python API so that you can control the motor drives from another script or program.  Best of all, since it's still based on GeckoMotion, you can use GeckoMotion scripts and access the full complement of the motor drives' features, such as vectored motion and homing.  Hope this is useful to you!

**Comment by scivision** [comment]
Thanks very much, I made a note of your library in the Readme.
